services:
  php:
    image: ghcr.io/blumilksoftware/php:8.3
    container_name: blt-php
    working_dir: /application
    user: ${CURRENT_UID}
    volumes:
      - .:/application
      - /home/jakub/coodestyle:/home/jakub/codestyle