version: "3.7"

services:
  php:
    image: ghcr.io/blumilksoftware/php:8.0.3.1
    container_name: behat-toolbox-php
    working_dir: /application
    user: ${CURRENT_UID}
    volumes:
      - .:/application
